### PR TITLE
Feature api

### PR DESCRIPTION
**Pull request by cyberz3r0**
- Implemented OpenWeather API utilizing axios
- Basic Error handling

### CODE REVIEW

**Comment by arize99** [comment]
Nice one Cyberz3r0 can you check again on the code? It seems to have some orphans.

**Comment by jameydev** [comment]
LGTM! The app seems off to a great start! Hope this PR gets approved. I didn't think to add node to this project. I probably was just going to use FetchAPI but you took me up on my challenge. Nicely done! One thing I'd suggest to avoid accidental pushes of API keys or node_modules folder is to use a .gitignore file and environment variables like with dotenv. Good you removed it though. Perhaps the project itself needs a .gitignore? Anyway, great work.

**Comment by cyberz3r0** [comment]
> LGTM! The app seems off to a great start! Hope this PR gets approved. I didn't think to add node to this project. I probably was just going to use FetchAPI but you took me up on my challenge. Nicely done! One thing I'd suggest to avoid accidental pushes of API keys or node_modules folder is to use a .gitignore file and environment variables like with dotenv. Good you removed it though. Perhaps the project itself needs a .gitignore? Anyway, great work.

I initially thought to use dotenv originally but after looking into it, it wasn't possible to have a dotenv as require is specific to Node. Since this is browser JS, require doesn't work. So we need server side setup if you want to take up that challenge.

**Comment by cyberz3r0** [comment]
@arize99 Looks like we may need to do some server side setup to hide the api key but for now, I rather leave the api_key as a fill until we have some security. Other than that, is this good to go?

**Comment by arize99** [comment]
Thanks for the contribution guys, I'll check the branches and merge them as soon as possible. Good Motivation 💪

**Comment by jameydev** [comment]
> @arize99 Looks like we may need to do some server side setup to hide the api key but for now, I rather leave the api_key as a fill until have some security. Other than that, is this good to go?

I completely agree. I also put in a PR earlier today with a .gitignore starter too.

EDIT: MERN is my favorite stack so far and the one I've worked with the most. I can help with node. We could use MERN or do something with handlebars templates for the frontend.

EDIT 2: My PR now includes what I did to get us started with MERN. Hope ya'll are interested in it for this project because, as I said, it's my favorite stack.

**Comment by cyberz3r0** [comment]
Due to recent changes to the project, I may revise and come back.

**Pull request closed without merging**
