### PR TITLE
added a starter .gitignore that might be helpful for all contributors AND MERNified the project

### PR DESCRIPTION
**Pull request by jameydev**
I think we should consider having a standard .gitignore available in the project so we can avoid accidentally pushing API keys, node_modules, etc to the repo. I quickly typed this up as it is what I generally use. There's another pull request out where someone else got to the API before me and they had accidentally committed that stuff before fixing it. I hope this starter .gitignore will be helpful. New developers or people new to github may not know about this so having it there by default would be great for code quality, IMHO.

EDIT:
Also revamped the project to use MERN as discussed on cyberz PR. Just an idea and you don't have to accept it, but it seems like vanillajs isn't enough. I think what I have will be a great start for using MERN for a SPA that gets weather data.

### CODE REVIEW

**Comment by jameydev** [comment]
Is this not going to work for you? Nobody's commented or anything on this PR. I'm considering closing it and doing a different version of the project that uses MERN. If you want this, the merge conflicts are the main obstacle here. Nobody has contacted me about this. I'll close this PR in a few days if nobody else does. Please let me know, all. Thanks!

**Comment by cyberz3r0** [comment]
@jameydev I have no problem with MERNing the project. I just don't know the scope of the project, whether, this is gonna be strictly VanillaJS or we are allowed to go further. Since arize is the only one who can approve PRs I was hoping he would give more feedback on your approach. @arize99 If you can clarify the scope of the project I'm sure there will be more contributions.

**Comment by arize99** [comment]
Hi @jameydev @cyberz3r0  I am sorry, I lost track of your PR. I am very sorry I didn't quite mention the scope of the project initially. I intended for this project to be simple and I was planning on creating a more advanced one. I wanted to ask you to Fork and MERN it but it skipped my mind.
Having a Full stack version and a Frontend version will go a long way to teach anyone who has been following.

**Comment by arize99** [comment]
Please Fork it so that I can link the Forked version to the Readme and other sources.

**Pull request closed without merging**
